version: '3'
services:

  em_rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  em_postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - ./.tmp/data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432